/* couponData.ts — DiscountHub Coupon Programs
 * Auto-generated from research data
 */

export type CouponAudience = 'senior' | 'disability' | 'both';

export interface CouponItem {
  name: string;
  type: string;
  discount: string;
  eligibility: string;
  how_to_access: string;
  website: string;
  audience: CouponAudience;
  notes?: string;
}

export interface CouponCategory {
  id: string;
  category: string;
  icon: string;
  coupons: CouponItem[];
}

export const COUPON_DATA: CouponCategory[] = [
  {
    id: "grocery-food",
    category: "Grocery & Food",
    icon: "ShoppingCart",
    coupons: [
      {
        name: "Kroger Senior Discount Days",
        type: "In-store discount",
        discount: "5% off",
        eligibility: "55+ (dates and eligibility vary by state)",
        how_to_access: "In-store, check with local store for specific days",
        website: "https://www.kroger.com/",
        audience: "senior",
        notes: "Occasionally offered, dates and eligibility vary by state.",
      },
      {
        name: "Kroger Digital Coupons",
        type: "Digital coupons",
        discount: "Varies",
        eligibility: "All customers",
        how_to_access: "Kroger app or website",
        website: "https://www.kroger.com/savings/cl/coupons/",
        audience: "both",
        notes: "Regularly available for groceries and household items.",
      },
      {
        name: "Kroger Plus Membership",
        type: "Loyalty program",
        discount: "Digital coupons, free grocery pickup, fuel points",
        eligibility: "All customers",
        how_to_access: "Sign up in-store or online",
        website: "https://www.kroger.com/pr/free-membership",
        audience: "both",
        notes: "Free membership with various benefits.",
      },
      {
        name: "Safeway Senior Discount Days",
        type: "In-store discount",
        discount: "10% off",
        eligibility: "62+ or 55+ (varies by location)",
        how_to_access: "In-store, check with local store for specific days (often first Wednesday of month)",
        website: "https://www.safeway.com/",
        audience: "senior",
        notes: "Discount days and eligibility vary by location.",
      },
      {
        name: "Publix Senior Discount",
        type: "In-store discount",
        discount: "5% off",
        eligibility: "60+ (where available)",
        how_to_access: "In-store, ask cashier. Check with local store for participation",
        website: "https://www.publix.com/savings",
        audience: "senior",
        notes: "Not corporate-wide, varies significantly by individual store location and state.",
      },
      {
        name: "Albertsons Senior Discount Days",
        type: "In-store discount",
        discount: "10% off",
        eligibility: "55+ or 65+ (varies by location)",
        how_to_access: "In-store, check with local store for specific days (often first Wednesday or Thursday of month). Some locations have dedicated senior/disabled shopping hours.",
        website: "https://www.albertsons.com/",
        audience: "both",
        notes: "Discounts and eligibility vary significantly by individual store location.",
      },
      {
        name: "Winn-Dixie Senior Discount Days",
        type: "In-store discount, digital coupons, loyalty program",
        discount: "5% off (where available), personalized deals, digital coupons",
        eligibility: "Seniors (age varies by location, typically 55+ or 60+)",
        how_to_access: "In-store, check with local store for specific days. Sign up for Winn-Dixie Rewards.",
        website: "https://www.winndixie.com/",
        audience: "senior",
        notes: "Discounts and eligibility vary by location. Winn-Dixie Rewards program offers additional savings.",
      },
      {
        name: "Senior Farmers' Market Nutrition Program (SFMNP)",
        type: "Vouchers/benefits for fresh produce",
        discount: "Varies by state (e.g., $20-$50 per year)",
        eligibility: "Low-income seniors (age 60+)",
        how_to_access: "Apply through state agencies. Benefits can be used at farmers' markets.",
        website: "https://www.fns.usda.gov/sfmnp/senior-farmers-market-nutrition-program",
        audience: "senior",
        notes: "Provides access to locally grown fruits, vegetables, honey, and herbs.",
      },
      {
        name: "Supplemental Nutrition Assistance Program (SNAP)",
        type: "Food assistance benefits (EBT card)",
        discount: "Varies based on income and household size",
        eligibility: "Low-income individuals and families. Special rules for elderly (60+) or disabled individuals may increase benefits.",
        how_to_access: "Apply through state social services agencies. Benefits are loaded onto an EBT card.",
        website: "https://www.fns.usda.gov/snap/recipient/eligibility",
        audience: "both",
        notes: "Helps low-income individuals and families purchase food. Eligibility and benefit amounts vary by state.",
      },
      {
        name: "Kroger Senior Discount (Local/Varies)",
        type: "In-store discount (varies by location)",
        discount: "Varies (some stores offer 5-10% on certain days)",
        eligibility: "Seniors (age varies, often 55+ or 60+)",
        how_to_access: "Inquire at participating locations on designated senior days",
        website: "https://No corporate senior discount policy; information found on local store promotions and community forums.",
        audience: "senior",
        notes: "Kroger does not have a company-wide senior discount. Some individual stores may offer discounts on specific days. It is essential to check with the local store for current offers and eligibility.",
      },
      {
        name: "Publix Senior Discount (Local/Varies)",
        type: "In-store discount (varies by location)",
        discount: "Varies (some stores offer 5% on certain days)",
        eligibility: "Seniors (age varies, often 60+ or 65+)",
        how_to_access: "Inquire at participating locations on designated senior days",
        website: "https://No corporate senior discount policy; information found on local store promotions and community forums.",
        audience: "senior",
        notes: "Publix does not have a company-wide senior discount. Some individual stores may offer discounts on specific days. It is essential to check with the local store for current offers and eligibility.",
      },
      {
        name: "Safeway Senior Discount (Local/Event-based)",
        type: "In-store discount",
        discount: "10% off (typically)",
        eligibility: "Seniors (age 62+ or 65+, varies by location and event)",
        how_to_access: "On designated senior days (e.g., first Tuesday or Wednesday of the month) at participating locations. Customers should inquire at their local Safeway.",
        website: "https://No dedicated corporate page for a universal senior discount. Information found on local store promotions and senior discount guides.",
        audience: "senior",
        notes: "Discount days and eligibility may vary by store. It is recommended to check with the local Safeway store for current offers.",
      },
      {
        name: "Senior Farmers' Market Nutrition Program (SFMNP)",
        type: "Food assistance program (coupons)",
        discount: "$20-$50 per year (varies by state) for fresh fruits, vegetables, honey, and herbs",
        eligibility: "Low-income seniors (age 60+)",
        how_to_access: "Receive coupons from state agencies, use at authorized farmers' markets, roadside stands, and community supported agriculture (CSA) programs",
        website: "https://www.fns.usda.gov/sfmnp/senior-farmers-market-nutrition-program",
        audience: "senior",
        notes: "Designed to provide low-income seniors with access to locally grown produce.",
      },
      {
        name: "Supplemental Nutrition Assistance Program (SNAP)",
        type: "Food assistance program (benefits on EBT card)",
        discount: "Varies based on income and household size",
        eligibility: "Low-income individuals and families, including seniors (60+) and people with disabilities. Special rules apply for elder",
        how_to_access: "Apply through state agencies, benefits loaded onto an EBT card for use at authorized grocery stores and farmers' markets.",
        website: "https://www.fns.usda.gov/snap/eligibility/elderly-disabled-special-rules (USDA FNS)",
        audience: "both",
        notes: "Provides nutritional support for eligible low-income individuals. Eligibility and benefit amounts vary by state and individual circumstances.",
      },
      {
        name: "Kroger Senior Discount Days",
        type: "In-store discount",
        discount: "5% off",
        eligibility: "55+ or 65+ years old (varies by location and event)",
        how_to_access: "In-store on specific senior discount days (check local store for details)",
        website: "https://www.kroger.com/",
        audience: "senior",
        notes: "Occasional events, not a regular program. Age requirement may vary.",
      },
      {
        name: "Safeway Senior Discount Days",
        type: "In-store discount",
        discount: "10% off",
        eligibility: "55+ years old",
        how_to_access: "In-store on the first and third Wednesdays of each month (check local store for details)",
        website: "https://www.safeway.com/",
        audience: "senior",
        notes: "Excludes alcohol and tobacco products. Varies by location.",
      },
      {
        name: "Publix Senior Shopping Hours",
        type: "Special shopping hours",
        discount: "N/A (no direct discount, but dedicated shopping time)",
        eligibility: "65+ years old",
        how_to_access: "In-store on Tuesdays and Wednesdays, 7-8 a.m.",
        website: "https://corporate.publix.com/newsroom/news-stories/senior-shopping-hours",
        audience: "senior",
        notes: "Dedicated shopping time, not a discount program.",
      },
      {
        name: "Senior Farmers' Market Nutrition Program (SFMNP)",
        type: "Vouchers/Coupons",
        discount: "$20-$50 per year (varies by state)",
        eligibility: "Low-income seniors (60+ years old)",
        how_to_access: "Apply through state agencies (e.g., local WIC office, Area Agency on Aging)",
        website: "https://www.fns.usda.gov/sfmnp/senior-farmers-market-nutrition-program",
        audience: "senior",
        notes: "Provides access to locally grown fruits, vegetables, honey, and herbs.",
      },
      {
        name: "Supplemental Nutrition Assistance Program (SNAP)",
        type: "EBT card benefits",
        discount: "Varies based on income and household size",
        eligibility: "Low-income individuals and families, special rules for 60+ or disabled",
        how_to_access: "Apply through state SNAP agencies",
        website: "https://www.fns.usda.gov/snap/eligibility/elderly-disabled-special-rules",
        audience: "both",
        notes: "Can receive a larger allotment if household includes an elderly or disabled person.",
      },
      {
        name: "ACME Markets",
        type: "Loyalty Program",
        discount: "Savings each week in coupons and deals; earn points, and redeem rewards for discounts on gas or groc",
        eligibility: "just for U reward card member",
        how_to_access: "In-store, just for U reward card",
        website: "https://www.acmemarkets.com/",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
      {
        name: "Albertsons",
        type: "Loyalty Program",
        discount: "Savings each week in coupons and deals; earn points, and redeem rewards for discounts on gas or groc",
        eligibility: "just for U reward card member",
        how_to_access: "In-store, just for U reward card",
        website: "https://www.albertsons.com/",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
      {
        name: "Food Lion",
        type: "Loyalty Program",
        discount: "Receive personalized savings and ways to earn rewards each month",
        eligibility: "Shop & Earn MVP Monthly Rewards card member",
        how_to_access: "In-store, Shop & Earn MVP Monthly Rewards card",
        website: "https://www.foodlion.com/",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
      {
        name: "Fred Meyer",
        type: "Senior Discount",
        discount: "Save 10% on select items",
        eligibility: "55+ years",
        how_to_access: "In-store",
        website: "https://www.fredmeyer.com/",
        audience: "senior",
        notes: "Discount availability: First Tuesday of the month",
      },
      {
        name: "Kroger",
        type: "Loyalty Program",
        discount: "Save with coupons and special promos; earn cash back, fuel points, and community rewards",
        eligibility: "Shopper's card member",
        how_to_access: "In-store, Shopper's card",
        website: "https://www.kroger.com/",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
      {
        name: "New Seasons Markets",
        type: "Senior Discount",
        discount: "Seniors save 10% on most items on Wednesdays",
        eligibility: "65+ years",
        how_to_access: "In-store",
        website: "https://www.newseasonsmarket.com/",
        audience: "senior",
        notes: "Discount availability: Every Wednesday",
      },
      {
        name: "Publix",
        type: "Loyalty Program",
        discount: "Savings each week with coupons and deals",
        eligibility: "Club Publix reward card member",
        how_to_access: "In-store, Club Publix reward card",
        website: "https://www.publix.com/",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
      {
        name: "Safeway",
        type: "Loyalty Program",
        discount: "Savings each week in coupons and deals; Earn points and redeem rewards for discounts on gas or groce",
        eligibility: "just for U reward card member",
        how_to_access: "In-store, just for U reward card",
        website: "https://www.safeway.com/",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
    ],
  },
  {
    id: "pharmacy-health",
    category: "Pharmacy & Health",
    icon: "HeartPulse",
    coupons: [
      {
        name: "CVS ExtraCare",
        type: "Loyalty program, digital coupons",
        discount: "Varies (ExtraBucks rewards, personalized deals, digital coupons)",
        eligibility: "All customers",
        how_to_access: "Sign up for ExtraCare card in-store or online. Use CVS app.",
        website: "https://www.cvs.com/extracare/overview",
        audience: "both",
        notes: "While not a specific senior discount, ExtraCare offers significant savings.",
      },
      {
        name: "Walgreens Seniors Day",
        type: "In-store and online discount",
        discount: "20% off eligible regular-priced merchandise",
        eligibility: "myWalgreens members 55+",
        how_to_access: "In-store (inform cashier) or online (use promo code SENIOR20). First Tuesday of each month.",
        website: "https://www.walgreens.com/topic/promotion/seniorday.jsp",
        audience: "senior",
        notes: "Requires myWalgreens membership. Discount applies to regular-priced items.",
      },
      {
        name: "Rite Aid Wellness 65+",
        type: "Loyalty program benefits",
        discount: "5x points on qualifying purchases, 10% off certain days",
        eligibility: "Wellness+ members 65+",
        how_to_access: "Enroll in Wellness 65+ program. Benefits apply on specific days (e.g., first Wednesday of every month).",
        website: "https://www.riteaid.com/",
        audience: "senior",
        notes: "Offers expanded pharmacist consultation and specific discount days. Check local store for full details.",
      },
      {
        name: "NeedyMeds",
        type: "Aggregator of manufacturer coupons, patient assistance progr",
        discount: "Varies by medication and program",
        eligibility: "Varies by program (often income-based or for specific conditions)",
        how_to_access: "Search their website for specific medications or medical supplies. Follow instructions for each program.",
        website: "https://www.needymeds.org/search-programs?initialSearchTab=coupons",
        audience: "both",
        notes: "Comprehensive resource for finding financial assistance for medications and healthcare costs.",
      },
      {
        name: "SingleCare",
        type: "Prescription discount card/coupons",
        discount: "Up to 80% off prescriptions",
        eligibility: "Anyone can use",
        how_to_access: "Visit website, search for medication, get coupon, present at pharmacy.",
        website: "https://www.singlecare.com/",
        audience: "both",
        notes: "Provides discounts on both generic and brand-name prescriptions.",
      },
      {
        name: "AARP Member Prescription Discounts (Optum Rx)",
        type: "Prescription discount card",
        discount: "Savings on all FDA-approved medications",
        eligibility: "AARP members",
        how_to_access: "Free prescription discount card provided by Optum Rx to AARP members. Use at participating pharmacies.",
        website: "https://www.aarp.org/membership/benefits/health/rx-discounts-optumrx/",
        audience: "senior",
        notes: "Can be used at over 66,000 pharmacies nationwide.",
      },
      {
        name: "Dexcom Savings Program",
        type: "Manufacturer coupon for Continuous Glucose Monitoring (CGM) ",
        discount: "Save $210+ on every 30-day supply of sensors; save more than $200 on transmitters",
        eligibility: "Patients with a prescription for Dexcom products",
        how_to_access: "Obtain a coupon from the Dexcom website and present it with a prescription.",
        website: "https://www.dexcom.com/en-us/savings-center",
        audience: "both",
        notes: "Significant savings on essential diabetes management supplies.",
      },
      {
        name: "CVS Senior Discount (AARP & ExtraCare)",
        type: "Loyalty Program / Partner Discount",
        discount: "Varies (AARP members get 10% off CVS Health brand products; ExtraCare offers personalized deals)",
        eligibility: "AARP members (for AARP discount); anyone can join ExtraCare",
        how_to_access: "Show AARP card for AARP discount; use ExtraCare card for ExtraCare deals",
        website: "https://www.cvs.com/ (AARP benefits mentioned on AARP website)",
        audience: "senior",
        notes: "CVS does not have a universal senior discount. Discounts are primarily through AARP partnership or general ExtraCare program.",
      },
      {
        name: "Friends of Disabled Adults and Children (FODAC)",
        type: "Non-profit program",
        discount: "Provides durable and affordable medical equipment",
        eligibility: "Persons with disabilities",
        how_to_access: "Contact FODAC for assistance",
        website: "https://Mentioned in Dealhack guide (source for medical supplies)",
        audience: "disability",
        notes: "Focuses on providing medical equipment.",
      },
      {
        name: "MTS Medical Supply",
        type: "Online Retail Discount",
        discount: "Discounted medical equipment and supplies, free shipping on select orders",
        eligibility: "Persons with disabilities",
        how_to_access: "Online purchase",
        website: "https://Mentioned in Dealhack guide (source for medical supplies)",
        audience: "disability",
        notes: "Offers discounted medical equipment and supplies with free shipping on some orders.",
      },
      {
        name: "Extract Labs Discount Program",
        type: "Online Discount (promo code)",
        discount: "50% off CBD products",
        eligibility: "Veterans and disabled individuals",
        how_to_access: "Sign up on their website and verify eligibility",
        website: "https://www.extractlabs.com/discount-programs/",
        audience: "disability",
        notes: "Requires verification of veteran or disabled status.",
      },
      {
        name: "Patient Advocate Foundation Financial Aid Funds",
        type: "Financial Aid (grants)",
        discount: "Small grants to assist with medical-related costs",
        eligibility: "Patients who meet financial and medical criteria",
        how_to_access: "Apply through their website",
        website: "https://www.patientadvocate.org/connect-with-services/financial-aid-funds/",
        audience: "both",
        notes: "Provides financial assistance for various medical needs, not limited to specific products.",
      },
      {
        name: "Rite Aid Rewards 65+",
        type: "Loyalty Program",
        discount: "5x points on eligible in-store purchases (first Wednesday of every month); some sources mention 20% ",
        eligibility: "Age 65 and older, Rite Aid Rewards member",
        how_to_access: "Join Rite Aid Rewards 65+ program, use loyalty card in-store on designated days.",
        website: "https://No specific program page found, but mentioned on various senior discount guides and Rite Aid's general rewards information.",
        audience: "senior",
        notes: "Benefits include earning accelerated reward points and potentially a discount on certain items. It's advisable to confirm the 20% discount with a local store.",
      },
      {
        name: "Walgreens Seniors Day",
        type: "Loyalty Program (myWalgreens) / In-store & Online Discount",
        discount: "20% off eligible regular-priced merchandise",
        eligibility: "myWalgreens members aged 55 and older",
        how_to_access: "First Tuesday of each month, in-store (let cashier know) or online (use promo code SENIOR20)",
        website: "https://www.walgreens.com/topic/promotion/seniorday.jsp",
        audience: "senior",
        notes: "Discount applies to eligible regular-priced merchandise. Must be a myWalgreens member.",
      },
      {
        name: "CVS ExtraCare Pharmacy & Health Rewards",
        type: "Loyalty program",
        discount: "Varies (e.g., 20% off CVS Health brand items, occasional prescription discounts)",
        eligibility: "ExtraCare members, some prescription discounts for 65+",
        how_to_access: "Sign up for ExtraCare, use Rx discount card (AARP members)",
        website: "https://www.cvs.com/extracare/overview",
        audience: "senior",
        notes: "AARP members can access a free Rx discount card.",
      },
      {
        name: "Walgreens Seniors Day",
        type: "In-store and online discount",
        discount: "20% off eligible regular-priced merchandise",
        eligibility: "55+ years old, myWalgreens member",
        how_to_access: "In-store or online with code SENIOR20 on the first Tuesday of each month",
        website: "https://www.walgreens.com/topic/promotion/seniorday.jsp",
        audience: "senior",
        notes: "Limit one use per order, one use per account.",
      },
      {
        name: "Rite Aid Wellness65+ Wednesday",
        type: "In-store discount",
        discount: "20% off all qualifying purchases",
        eligibility: "65+ years old, Wellness+ member",
        how_to_access: "In-store on the first Wednesday of each month",
        website: "https://www.riteaid.com/",
        audience: "senior",
        notes: "Part of the Living More program.",
      },
      {
        name: "State Equipment Distribution Programs (e.g., tedpa.org)",
        type: "Free equipment",
        discount: "Free amplified telephones",
        eligibility: "U.S. residents with hearing impairments",
        how_to_access: "Via state programs (website: tedpa.org)",
        website: "https://www.tedpa.org/",
        audience: "disability",
        notes: "Most U.S. states currently have equipment distribution programs.",
      },
      {
        name: "U.S. Federal, State, Local, and Non-profit Home Accessibility Improvement Progra",
        type: "Assistance/Grants",
        discount: "Assistance with wheelchair ramps, handrails, grab bars, etc.",
        eligibility: "Elderly or disabled individuals in the U.S.",
        how_to_access: "Via federal, state, local, and non-profit organizations",
        website: "https://Not directly provided, requires further research for specific programs.",
        audience: "both",
        notes: "Programs assist with home accessibility improvements.",
      },
      {
        name: "NeedyMeds Drug Discount Card",
        type: "Discount Card",
        discount: "Up to 80% off prescription medications",
        eligibility: "Anyone can use it",
        how_to_access: "Get a free card from the NeedyMeds website",
        website: "https://www.needymeds.org/",
        audience: "disability",
        notes: "Provides significant discounts on prescription medications.",
      },
      {
        name: "NeedyMeds Patient Assistance Programs (PAPs)",
        type: "Assistance Program",
        discount: "Free or discounted medicines",
        eligibility: "Varies by program, generally for those in need",
        how_to_access: "Search programs on NeedyMeds website",
        website: "https://www.needymeds.org/",
        audience: "disability",
        notes: "Helps individuals get free or discounted medicines directly from pharmaceutical companies.",
      },
      {
        name: "NeedyMeds Diagnosis-Based Assistance",
        type: "Assistance Program",
        discount: "Help with diagnosis-related costs",
        eligibility: "Individuals with specific diagnoses",
        how_to_access: "Find programs on NeedyMeds website",
        website: "https://www.needymeds.org/",
        audience: "disability",
        notes: "Connects individuals with organizations offering help with diagnosis-related costs.",
      },
      {
        name: "NeedyMeds Coupons, Rebates & Co-pays",
        type: "Printable coupons, rebates, savings cards",
        discount: "Varies",
        eligibility: "Varies by offer",
        how_to_access: "Search on NeedyMeds website",
        website: "https://www.needymeds.org/",
        audience: "both",
        notes: "Aggregates various savings opportunities for medications and healthcare.",
      },
      {
        name: "GoodRx Prescription Savings Card/App",
        type: "Discount Card/Digital Coupon",
        discount: "Up to 80% off on most prescription drugs",
        eligibility: "Anyone can use it",
        how_to_access: "Get a free card from GoodRx website or use the mobile app",
        website: "https://www.goodrx.com/",
        audience: "disability",
        notes: "Works at over 70,000 U.S. pharmacies. No fees or credit card required.",
      },
      {
        name: "GoodRx for Medical Supplies and Devices",
        type: "Digital Coupons/Discounts",
        discount: "Varies, includes discounts on items like test strips, needles, and meters",
        eligibility: "Anyone can use it",
        how_to_access: "Search on GoodRx website or mobile app for specific product names",
        website: "https://www.goodrx.com/",
        audience: "both",
        notes: "Provides discounts on various medical supplies and devices.",
      },
      {
        name: "RxAssist Patient Assistance Programs",
        type: "Patient Assistance Program",
        discount: "Free medications",
        eligibility: "Individuals who cannot afford to buy their medicine (criteria vary by program)",
        how_to_access: "Search database on RxAssist website",
        website: "https://www.rxassist.org/",
        audience: "disability",
        notes: "Comprehensive database of pharmaceutical company patient assistance programs.",
      },
      {
        name: "Rite Aid Rewards 65+",
        type: "Loyalty Program",
        discount: "Earn 5x points, in-store purchases that day. Free pharmacist consultation to review medications, imm",
        eligibility: "65+ years; must enroll in-store for the wellness65+ and be a wellness+ member",
        how_to_access: "In-store",
        website: "https://www.riteaid.com/",
        audience: "senior",
        notes: "Discount availability: First Wednesday of each month",
      },
      {
        name: "Walgreens Seniors Day",
        type: "Senior Discount",
        discount: "20% off eligible items and cash rewards",
        eligibility: "55+ years or an AARP member; must create a myWalgreens account",
        how_to_access: "In-store and online",
        website: "https://www.walgreens.com/",
        audience: "senior",
        notes: "Discount availability: Check local Walgreens for schedule",
      },
      {
        name: "SilverSneakers",
        type: "Fitness Program",
        discount: "Free healthy living and fitness classes at over 17,000 fitness locations",
        eligibility: "65+ years and a member of select Medicare or other health plans",
        how_to_access: "In-person",
        website: "https://www.silversneakers.com/",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
      {
        name: "AARP Health and Wellness Discounts",
        type: "AARP Membership Benefits",
        discount: "Various discounts on health savings accounts, hearing care, vision, and prescription drugs",
        eligibility: "AARP member",
        how_to_access: "Online, In-store",
        website: "https://www.aarp.org/",
        audience: "senior",
        notes: "Includes CareLinx In-Home Care, HearUSA, Kroger Co. Pharmacy, LensCrafters, MyVision Care, OptumRx, Target Optical, Walmart Pharmacy",
      },
    ],
  },
  {
    id: "restaurants-dining",
    category: "Restaurants & Dining",
    icon: "UtensilsCrossed",
    coupons: [
      {
        name: "AARP Dining Program",
        type: "Membership discount",
        discount: "Up to 15% off food and non-alcoholic beverages",
        eligibility: "AARP members",
        how_to_access: "Show AARP membership card. Check AARP website for participating restaurants.",
        website: "https://www.aarp.org/membership/benefits/restaurants/",
        audience: "senior",
        notes: "Requires AARP membership. Discounts vary by restaurant.",
      },
      {
        name: "Denny's AARP Discount",
        type: "Partner Discount",
        discount: "15% off",
        eligibility: "AARP members",
        how_to_access: "Show AARP card",
        website: "https://www.dennys.com/blog/senior-citizen-restaurant-discounts-dennys",
        audience: "senior",
        notes: "Discount for AARP members. Some locations may offer additional senior menus or discounts.",
      },
      {
        name: "IHOP 55+ Menu",
        type: "Special Menu",
        discount: "Reduced prices on select menu items",
        eligibility: "Age 55+",
        how_to_access: "Order from the 55+ menu in-restaurant",
        website: "https://www.ihop.com/en/menu/55and-menu/55and-breakfast-sampler",
        audience: "senior",
        notes: "Not a percentage discount, but a menu with smaller portions and lower prices for seniors.",
      },
      {
        name: "McDonald's Senior Discount (Local/Varies)",
        type: "In-store discount (varies by location)",
        discount: "Discounted coffee or soft drinks, or other discounts",
        eligibility: "Seniors (age varies, often 55+ or 60+)",
        how_to_access: "Ask at participating locations",
        website: "https://No corporate senior discount policy; information found on local store promotions and senior discount guides.",
        audience: "senior",
        notes: "Discounts vary by location and are not a company-wide policy. Customers should inquire at their local McDonald's.",
      },
      {
        name: "Papa John's AARP Discount",
        type: "Partner Discount (promo code)",
        discount: "20% off regular menu prices",
        eligibility: "AARP members",
        how_to_access: "Use promo code (often AARP20) when ordering online or mention in-store",
        website: "https://AARP website, Papa John's website (check for current promotions)",
        audience: "senior",
        notes: "Discount may vary by location and is subject to change. Always confirm when ordering.",
      },
      {
        name: "Pizza Hut Senior Discount (Local/Varies)",
        type: "In-store discount (varies by location)",
        discount: "Varies (e.g., 10% off, discounted menu items)",
        eligibility: "Seniors (age varies, often 55+ or 60+)",
        how_to_access: "Ask at participating locations",
        website: "https://No corporate senior discount policy; information found on local store promotions and senior discount guides.",
        audience: "senior",
        notes: "Discounts vary by location and are not a company-wide policy. Customers should inquire at their local Pizza Hut.",
      },
      {
        name: "Subway Senior Discount (Local)",
        type: "In-store discount (varies by location)",
        discount: "10% off or free drink",
        eligibility: "Seniors (60+)",
        how_to_access: "Ask at participating locations",
        website: "https://Not a specific corporate page, but mentioned on various senior discount guides like https://caringseniorservice.com/blog/senior-discount-guide/",
        audience: "senior",
        notes: "Discount varies by location and is not a company-wide policy. Customers should inquire at their local Subway.",
      },
      {
        name: "Bubba Gump Shrimp Co.",
        type: "AARP Discount",
        discount: "Save 10% on food and nonalcoholic beverages",
        eligibility: "Present AARP card at checkout",
        how_to_access: "In-store",
        website: "https://www.bubbagump.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Bonefish Grill",
        type: "AARP Discount",
        discount: "Save 10% on food and nonalcoholic beverages",
        eligibility: "Present AARP card at checkout",
        how_to_access: "In-store",
        website: "https://www.bonefishgrill.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Carrabba's Italian Grill",
        type: "AARP Discount",
        discount: "Save 10% on food and nonalcoholic beverages",
        eligibility: "Present AARP card at checkout",
        how_to_access: "In-store",
        website: "https://www.carrabbas.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Chart House",
        type: "AARP Discount",
        discount: "Save 10% on food and nonalcoholic beverages",
        eligibility: "Present AARP card at checkout",
        how_to_access: "In-store",
        website: "https://www.charthouse.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Corner Bakery Cafe",
        type: "AARP Discount",
        discount: "Save 10% off your check",
        eligibility: "Present AARP card at checkout",
        how_to_access: "In-store",
        website: "https://www.cornerbakerycafe.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Denny's",
        type: "AARP Discount / Senior Menu",
        discount: "Save 15% off your check; dine from Denny's 55+ menu",
        eligibility: "Present AARP card to save 15%; 55+ years for the senior menu",
        how_to_access: "In-store",
        website: "https://www.dennys.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "El Pollo Loco",
        type: "Senior Discount",
        discount: "Save 10% (up to $1)",
        eligibility: "60+ years",
        how_to_access: "In-store",
        website: "https://www.elpolloloco.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "IHOP",
        type: "Senior Menu",
        discount: "Dine from IHOP's 55+ menu",
        eligibility: "55+ years",
        how_to_access: "In-store",
        website: "https://www.ihop.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Joe's Crab Shack",
        type: "AARP Discount",
        discount: "Save 10% on food and nonalcoholic beverages",
        eligibility: "Present AARP card at checkout",
        how_to_access: "In-store",
        website: "https://www.joescrabshack.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Landry's Seafood",
        type: "AARP Discount",
        discount: "Save 10% on food and nonalcoholic beverages",
        eligibility: "Present AARP card at checkout",
        how_to_access: "In-store",
        website: "https://www.landrysseafood.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Luby's",
        type: "Senior Special",
        discount: "Senior Luann Special $7.99 \u2013 3 p.m. to close",
        eligibility: "No requirements",
        how_to_access: "In-store",
        website: "https://www.lubys.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "McCormick & Schmick's",
        type: "AARP Discount",
        discount: "Save 10% on food and nonalcoholic beverages",
        eligibility: "Present AARP card at checkout",
        how_to_access: "In-store",
        website: "https://www.mccormickandschmicks.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Outback Steakhouse",
        type: "AARP Discount",
        discount: "Save 10% on food and nonalcoholic beverages",
        eligibility: "Present AARP card at checkout",
        how_to_access: "In-store",
        website: "https://www.outback.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Rainforest Cafe",
        type: "AARP Discount",
        discount: "Save 10% on food and nonalcoholic beverages",
        eligibility: "Present AARP card at checkout",
        how_to_access: "In-store",
        website: "https://www.rainforestcafe.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Saltgrass Steak House",
        type: "AARP Discount",
        discount: "Save 10% on food and nonalcoholic beverages",
        eligibility: "Present AARP card at checkout",
        how_to_access: "In-store",
        website: "https://www.saltgrass.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "The Oceanaire Seafood Room",
        type: "AARP Discount",
        discount: "Save 10% on food and nonalcoholic beverages",
        eligibility: "Present AARP card at checkout",
        how_to_access: "In-store",
        website: "https://www.theoceanaire.com/",
        audience: "senior",
        notes: "N/A",
      },
    ],
  },
  {
    id: "retail-shopping",
    category: "Retail & Shopping",
    icon: "ShoppingBag",
    coupons: [
      {
        name: "Kohl's Senior Discount Day",
        type: "In-store discount",
        discount: "15% off",
        eligibility: "60+",
        how_to_access: "Shop on Wednesdays, present ID.",
        website: "https://www.kohls.com/",
        audience: "senior",
        notes: "Discount applies to qualifying purchases.",
      },
      {
        name: "SeniorOwls",
        type: "Online coupon codes and deals",
        discount: "Varies by store and offer",
        eligibility: "50+ (senior citizens)",
        how_to_access: "Visit website, browse deals, use coupon codes online or in-store.",
        website: "https://www.seniorowls.com/us",
        audience: "senior",
        notes: "Compiles discounts from hundreds of popular stores, updated daily.",
      },
      {
        name: "TheSeniorList",
        type: "Comprehensive list of senior discounts",
        discount: "Varies by store and offer",
        eligibility: "Varies by discount (typically 50+ to 65+)",
        how_to_access: "Visit website, browse categories (car rentals, grocery stores, etc.).",
        website: "https://www.theseniorlist.com/senior-discounts/",
        audience: "senior",
        notes: "Provides a broad range of discounts across many categories.",
      },
      {
        name: "Beansid (Super Disability Discounts & Deals)",
        type: "Discount codes and deals",
        discount: "Varies (e.g., $55 off, 15% off, 10% off)",
        eligibility: "People with disabilities",
        how_to_access: "Verify disability status through Beansid, then access exclusive discounts.",
        website: "https://beansid.com/us/super-com/disability",
        audience: "disability",
        notes: "Requires verification of disability status to access deals.",
      },
      {
        name: "Adaptive Clothing Showroom Clearance",
        type: "Online Retail Discount",
        discount: "Varies (clearance prices)",
        eligibility: "General (focuses on adaptive clothing for seniors and disabled)",
        how_to_access: "Online purchase",
        website: "https://adaptiveclothingshowroom.com/clearance-adaptive-clothing/",
        audience: "both",
        notes: "Offers discounted easy-dressing clothing for men, women, and children.",
      },
      {
        name: "JCPenney Adaptive Clothing & Accessories",
        type: "Retail Collection",
        discount: "Standard pricing (not a specific discount program, but offers specialized products)",
        eligibility: "General (for individuals with sensory, dexterity, and/or mobility needs)",
        how_to_access: "Online or in-store purchase",
        website: "https://www.jcpenney.com/g/shops/adaptive-clothing-and-accessories?id=cat11100002883",
        audience: "both",
        notes: "Provides a vast assortment of adaptive clothing and accessories.",
      },
      {
        name: "Joe & Bella Adaptive Clothing",
        type: "Online Retail",
        discount: "Standard pricing (not a specific discount program, but offers specialized products)",
        eligibility: "General (for elderly and people with disability)",
        how_to_access: "Online purchase",
        website: "https://joeandbella.com/",
        audience: "both",
        notes: "Award-winning innovative and stylish adaptive clothing.",
      },
      {
        name: "Goodwill Senior Discount",
        type: "In-store discount",
        discount: "15-25% off (varies by store)",
        eligibility: "Shoppers age 55+ (days and discounts vary)",
        how_to_access: "Ask at your local Goodwill store on designated senior days",
        website: "https://Not a corporate-wide policy; mentioned on various senior discount guides (e.g., NCOA.org, SeniorLiving.org)",
        audience: "senior",
        notes: "Days and discount percentages vary by individual Goodwill store location. Always inquire at the store.",
      },
      {
        name: "Kohl's Senior Discount",
        type: "In-store discount",
        discount: "15% off",
        eligibility: "Age 60 or better",
        how_to_access: "Every Wednesday in stores",
        website: "https://www.kohls.com/faq/article/101",
        audience: "senior",
        notes: "Limit one per customer, dollar-off coupons and other exclusions may apply.",
      },
      {
        name: "Ross Dress for Less Senior Discount",
        type: "In-store discount",
        discount: "10% off",
        eligibility: "Age 55+",
        how_to_access: "On Tuesdays, ask at checkout",
        website: "https://Mentioned on various senior discount guides (e.g., TheSeniorList.com)",
        audience: "senior",
        notes: "Discount applies on Tuesdays for eligible seniors 10% off for 55+",
      },
      {
        name: "Kohl's Senior Discount",
        type: "In-store discount",
        discount: "15% off",
        eligibility: "60+ years old",
        how_to_access: "In-store on Wednesdays",
        website: "https://www.kohls.com/",
        audience: "senior",
        notes: "Excludes gift cards, Sephora, and certain items. Not valid online.",
      },
      {
        name: "JCPenney Senior Saturday (local)",
        type: "In-store discount",
        discount: "20% off",
        eligibility: "Seniors (age may vary by location)",
        how_to_access: "In-store on specific 'Senior Saturday' events. Check local store for details.",
        website: "https://www.jcpenney.com/",
        audience: "senior",
        notes: "Exclusions apply. Also, $35 off with JCP Card purchase. Varies by location.",
      },
      {
        name: "Target Optical Senior Discount",
        type: "In-store discount",
        discount: "Extra $10 off",
        eligibility: "55+ years old",
        how_to_access: "In-store at Target Optical",
        website: "https://www.target.com/",
        audience: "senior",
        notes: "Applies to a frame, lenses, or complete pair.",
      },
      {
        name: "Target Circle 360 Government Assistance Discount",
        type: "Membership discount",
        discount: "$4.99/month (vs $10.99/month)",
        eligibility: "Target Circle members with verified government assistance status (SNAP, Medicaid, etc.)",
        how_to_access: "Verify government assistance status through Target Circle account",
        website: "https://www.target.com/l/target-circle-360/-/N-2rguk",
        audience: "both",
        notes: "Provides benefits like free delivery.",
      },
      {
        name: "Walmart+ Assist Membership",
        type: "Membership discount",
        discount: "50% off yearly membership",
        eligibility: "Recipients of SNAP, Medicaid, and other government assistance programs",
        how_to_access: "Sign up for Walmart+ Assist and verify eligibility",
        website: "https://www.walmart.com/plus/assist",
        audience: "both",
        notes: "Includes perks like free delivery.",
      },
      {
        name: "Walmart+ AARP Member Discount",
        type: "Membership discount",
        discount: "$20 off annual Walmart+ membership",
        eligibility: "AARP members",
        how_to_access: "Through AARP membership benefits",
        website: "https://www.walmart.com/plus",
        audience: "senior",
      },
      {
        name: "SeniorOwls.com",
        type: "Coupon aggregator",
        discount: "Varies by offer",
        eligibility: "50+ years old",
        how_to_access: "Website (online codes, printable coupons)",
        website: "https://www.seniorowls.com/us",
        audience: "senior",
        notes: "Aggregates exclusive coupon codes and deals for seniors.",
      },
      {
        name: "AARP Member Benefits",
        type: "Membership discounts",
        discount: "Varies by offer (travel, dining, retail, insurance, etc.)",
        eligibility: "AARP membership (50+ years old)",
        how_to_access: "AARP website, membership card",
        website: "https://www.aarp.org/membership/benefits/all-offers-a-z/",
        audience: "senior",
        notes: "Comprehensive benefits across many categories for members.",
      },
      {
        name: "Disabled-World.com Discounts",
        type: "Information aggregator",
        discount: "Varies by offer",
        eligibility: "People with disabilities",
        how_to_access: "Website (information on various discounts)",
        website: "https://www.disabled-world.com/entertainment/discounts/",
        audience: "disability",
        notes: "Lists discounted and free access passes for disabled individuals including nature and theme parks, museums, cinemas, transportation, and other services.",
      },
      {
        name: "Goodwill Senior Savings Day",
        type: "Senior Discount",
        discount: "10% off your purchase",
        eligibility: "60+ years",
        how_to_access: "In-store",
        website: "https://www.goodwill.org/",
        audience: "senior",
        notes: "Discount availability: Tuesdays",
      },
      {
        name: "JOANN Senior Discount Day",
        type: "Senior Discount",
        discount: "20% off your purchase",
        eligibility: "55+ years; must present a state-issued photo ID",
        how_to_access: "In-store",
        website: "https://www.joann.com/",
        audience: "senior",
        notes: "Discount availability: Check local store for schedule",
      },
      {
        name: "Kohl's",
        type: "Senior Discount",
        discount: "15% off your purchase",
        eligibility: "60+ years; must present a state-issued photo ID",
        how_to_access: "In-store",
        website: "https://www.kohls.com/",
        audience: "senior",
        notes: "Discount availability: Wednesdays",
      },
      {
        name: "Ross Dress for Less 55+ Program",
        type: "Senior Discount",
        discount: "10% off your purchase",
        eligibility: "55+ years; must provide a photo ID",
        how_to_access: "In-store",
        website: "https://www.rossstores.com/",
        audience: "senior",
        notes: "Discount availability: Tuesdays",
      },
      {
        name: "Michaels",
        type: "Senior Discount",
        discount: "10% off your purchase",
        eligibility: "55+ years; Must create a Michaels Rewards account",
        how_to_access: "In-store and Online",
        website: "https://www.michaels.com/",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
      {
        name: "Red, White, and Blue Thrift Stores Senior Citizen Day",
        type: "Senior Discount",
        discount: "50% off your purchase",
        eligibility: "55+ years",
        how_to_access: "In-store",
        website: "https://N/A",
        audience: "senior",
        notes: "Discount availability: Wednesdays",
      },
      {
        name: "Savers",
        type: "Senior Discount",
        discount: "Percentage varies by store location",
        eligibility: "55+ years",
        how_to_access: "In-store",
        website: "https://www.savers.com/",
        audience: "senior",
        notes: "Discount availability: Tuesdays",
      },
      {
        name: "Tanger Outlets",
        type: "Coupon Book",
        discount: "Free Tanger coupon book with up to $1,000 in savings",
        eligibility: "AARP member",
        how_to_access: "In-store",
        website: "https://www.tangeroutlets.com/",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
    ],
  },
  {
    id: "travel-transportation",
    category: "Travel & Transportation",
    icon: "Plane",
    coupons: [
      {
        name: "U.S. National Park Service \"America The Beautiful Access Pass\"",
        type: "Free pass",
        discount: "Free access into national parks and federal recreational lands",
        eligibility: "Disabled U.S. residents",
        how_to_access: "Apply through NPS",
        website: "https://www.nps.gov/planyourvisit/passes.htm",
        audience: "disability",
        notes: "Provides free access to national parks and federal recreational lands.",
      },
      {
        name: "Amtrak Rail Fare Discounts",
        type: "Discounted fare",
        discount: "Various rail fare discounts",
        eligibility: "Varies, but includes people with disabilities",
        how_to_access: "Book through Amtrak",
        website: "https://www.amtrak.com/deals-discounts/everyday-discounts/passengers-with-disabilities-discount.html",
        audience: "disability",
        notes: "Amtrak offers several types of rail fare discounts.",
      },
      {
        name: "Carnival Cruise Line",
        type: "Senior Discount",
        discount: "Exclusive senior pricing on selected sailings",
        eligibility: "55+ years",
        how_to_access: "Online",
        website: "https://www.carnival.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Collette Cruise Tours",
        type: "AARP Discount",
        discount: "Combine two cruise tours and save up to $300 per person on your second tour and subsequent tours.",
        eligibility: "AARP member",
        how_to_access: "Online",
        website: "https://www.gocollette.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Grand European Travel",
        type: "AARP Discount",
        discount: "Offers a variety of discounts throughout the year. You can currently save up to 15% on worldwide tou",
        eligibility: "AARP member",
        how_to_access: "Online",
        website: "https://www.grandeuropeantravel.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Royal Caribbean",
        type: "Senior Discount",
        discount: "Exclusive senior pricing on selected sailings",
        eligibility: "55+ years",
        how_to_access: "Online",
        website: "https://www.royalcaribbean.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Vacations By Rail",
        type: "AARP Discount",
        discount: "Save up to $500 on more than 40 rail and cruise vacations",
        eligibility: "AARP member",
        how_to_access: "Online",
        website: "https://www.vacationsbyrail.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Avis Rent a Car",
        type: "AARP Discount",
        discount: "Save up to 30% off Avis' base rates, plus get an upgrade on compact through full-size car class book",
        eligibility: "AARP member",
        how_to_access: "Online",
        website: "https://www.avis.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Budget Rent a Car",
        type: "AARP Discount",
        discount: "Save up to 35% off Budget's base rates, plus get an upgrade on compact through full-size car class b",
        eligibility: "AARP member",
        how_to_access: "Online",
        website: "https://www.budget.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Budget Truck Rental",
        type: "AARP Discount",
        discount: "Save 10% to 20% on truck rentals",
        eligibility: "AARP member",
        how_to_access: "Online",
        website: "https://www.budgettruck.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Best Western Hotels & Resorts",
        type: "AARP Discount",
        discount: "Save 5% to 15% at over 4,000 hotels worldwide",
        eligibility: "AARP member",
        how_to_access: "Online",
        website: "https://www.bestwestern.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Cambria Hotels",
        type: "AARP Discount",
        discount: "Save up to 10% off the best available rate",
        eligibility: "AARP member",
        how_to_access: "Online",
        website: "https://www.choicehotels.com/cambria",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Choice Hotels",
        type: "Senior Discount / AARP Discount",
        discount: "Save 10% on advance reservations",
        eligibility: "60+ years or an AARP member",
        how_to_access: "Online",
        website: "https://www.choicehotels.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Hertz",
        type: "Senior Discount",
        discount: "Save up to 20% off Hertz's base rates with the Fifty Plus Program",
        eligibility: "50+ years",
        how_to_access: "Online",
        website: "https://www.hertz.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "IHG Hotels & Resorts",
        type: "Senior Discount",
        discount: "Save with IHG's Senior Discount Rate program",
        eligibility: "62+ years",
        how_to_access: "Online",
        website: "https://www.ihg.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Marriott",
        type: "Senior Discount",
        discount: "Offers a senior discount rate at participating locations",
        eligibility: "62+ years",
        how_to_access: "Online",
        website: "https://www.marriott.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Payless Car Rental",
        type: "AARP Discount",
        discount: "Save 5% on leisure daily, weekly, weekend, and monthly base rates, plus get a free upgrade on compac",
        eligibility: "AARP member",
        how_to_access: "Online",
        website: "https://www.paylesscar.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Thrifty Car Rental",
        type: "Senior Discount",
        discount: "Join the Silver Thrifty Club and save 5%",
        eligibility: "50+ years",
        how_to_access: "Online",
        website: "https://www.thrifty.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Wyndham Hotels",
        type: "AARP Discount",
        discount: "Save 10% off Wyndham's best available rate",
        eligibility: "AARP member",
        how_to_access: "Online",
        website: "https://www.wyndhamhotels.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Zipcar",
        type: "AARP Discount",
        discount: "$40 for an annual Zipcar membership, plus $40 in free driving credit",
        eligibility: "AARP member",
        how_to_access: "Online",
        website: "https://www.zipcar.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Amtrak",
        type: "Senior Discount",
        discount: "Save 10% on most rail fares on most Amtrak trains",
        eligibility: "65+ years",
        how_to_access: "Online",
        website: "https://www.amtrak.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "British Airways",
        type: "AARP Discount",
        discount: "Save $65 off World Traveller (economy) and World Traveller Plus (premium economy) or $200 off Club W",
        eligibility: "AARP member",
        how_to_access: "Online",
        website: "https://www.britishairways.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Delta Airlines",
        type: "Senior Discount",
        discount: "Senior discounts are available for limited itineraries",
        eligibility: "Call Delta's customer care at (800) 221-1212 to find out if your flight is eligible for the discounted fare",
        how_to_access: "Phone",
        website: "https://www.delta.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "United Airlines",
        type: "Senior Discount",
        discount: "Save on senior fares to select travel destinations",
        eligibility: "65+ years",
        how_to_access: "Online",
        website: "https://www.united.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Amtrak Disability Discount",
        type: "Disability Discount",
        discount: "Up to 60% off for adult and child passengers with disabilities",
        eligibility: "Passengers with disabilities",
        how_to_access: "Online, at station, or by phone",
        website: "https://www.amtrak.com/",
        audience: "disability",
        notes: "Discount varies by age and distance",
      },
      {
        name: "ClubGO",
        type: "Travel Platform Discount",
        discount: "Up to 60% off select hotels, resorts and motels",
        eligibility: "ClubGO members, specifically for people with disabilities",
        how_to_access: "Membership to ClubGO and use of accessibleGO travel platform",
        website: "https://accessiblego.com/",
        audience: "disability",
        notes: "Accessible travel platform",
      },
      {
        name: "Eurostar Disability Discount",
        type: "Travel Discount",
        discount: "Standard Premier and Business Premier seating for the price of a Standard Class ticket",
        eligibility: "Passengers in wheelchairs",
        how_to_access: "Book through Eurostar",
        website: "https://www.eurostar.com/",
        audience: "disability",
        notes: "For trips to Europe",
      },
      {
        name: "Greyhound Disability Services",
        type: "Travel Services",
        discount: "Priority seating, assistance during stops, and other services",
        eligibility: "Passengers with disabilities",
        how_to_access: "Contact Greyhound for assistance",
        website: "https://www.greyhound.com/",
        audience: "disability",
        notes: "N/A",
      },
      {
        name: "Interagency Senior Annual and Senior Lifetime Passes (National Park Service)",
        type: "Pass (physical or digital)",
        discount: "Covers entrance and standard amenity (day-use) recreation fees, and provides discounts on some expan",
        eligibility: "US citizens or residents 62 years or older.",
        how_to_access: "In-person at federal recreation sites, order online at USGS Online Store (physical pass by mail), or get a Digital Pass from Recreation.gov.",
        website: "https://www.nps.gov/planyourvisit/senior-pass-changes.htm",
        audience: "senior",
        notes: "Senior Lifetime Pass costs $80, Senior Annual Pass costs $20. Old Golden Age Passports are still valid and can be exchanged for a new Senior Lifetime Pass for free.",
      },
      {
        name: "Amtrak Disability Discount",
        type: "Discount",
        discount: "15% off the lowest available rail fare",
        eligibility: "Persons with physical or mental disabilities (official documentation required)",
        how_to_access: "Online or at ticket counter",
        website: "https://www.amtrak.com/passengers-with-disabilities-discounts",
        audience: "disability",
      },
      {
        name: "America the Beautiful \u2013 National Parks & Federal Recreational Lands Access Pass",
        type: "Pass",
        discount: "Free access to many national parks, discounts on campsites and other amenities",
        eligibility: "U.S. citizens or permanent residents with a permanent disability \u201cthat severely limits one or more major life activities",
        how_to_access: "Online or during a visit to a national park",
        website: "https://www.nps.gov/subjects/accessibility/interagency-access-pass.htm",
        audience: "disability",
      },
      {
        name: "California State Parks Disabled Discount Pass",
        type: "Pass",
        discount: "50% discount on vehicle day use, family camping, and boat fees",
        eligibility: "Individuals with disabilities",
        how_to_access: "Apply for the pass",
        website: "https://www.parks.ca.gov/30236",
        audience: "disability",
      },
      {
        name: "New York State Parks Access Pass",
        type: "Pass",
        discount: "Free or discounted use of state parks, historic sites, and recreational facilities",
        eligibility: "Residents of New York State with disabilities",
        how_to_access: "Apply for the pass",
        website: "https://parks.ny.gov/admission/access-pass/",
        audience: "disability",
      },
      {
        name: "Vermont Metered Parking Disability Discount",
        type: "Free Parking",
        discount: "Free metered parking",
        eligibility: "Drivers with an accessible parking placard or license plate",
        how_to_access: "Display placard/license plate",
        website: "https://parkburlington.com/links-resources/faq/",
        audience: "disability",
      },
      {
        name: "Regional Transportation Authority (Chicago) Disability Discount",
        type: "Free/Reduced Fare",
        discount: "Free or reduced fare",
        eligibility: "People with disabilities",
        how_to_access: "Apply for program",
        website: "https://www.rtachicago.org/riders/free-and-reduced-fare-programs",
        audience: "disability",
      },
      {
        name: "New York Ferry System Disability Discount",
        type: "Discounted Fare",
        discount: "Discounted fare",
        eligibility: "Individuals with a disability",
        how_to_access: "Apply for discount",
        website: "https://www.ferry.nyc/discount/",
        audience: "disability",
      },
      {
        name: "TriMet (Portland) Disability Discount",
        type: "Discounted Fare",
        discount: "50-70% off fares",
        eligibility: "Individuals with disabilities (proof of eligibility required)",
        how_to_access: "Apply for Honored Citizen fare",
        website: "https://trimet.org/fares/honoredcitizen.htm",
        audience: "disability",
      },
      {
        name: "American Airlines Senior Discount",
        type: "Discount",
        discount: "Various discounts (call directly)",
        eligibility: "65 and up (certain markets and flights)",
        how_to_access: "Call directly",
        website: "https://(No direct link, call American Airlines)",
        audience: "senior",
      },
      {
        name: "Southwest Airlines Senior Discount",
        type: "Discount",
        discount: "Various discounts (call to apply)",
        eligibility: "65 and up",
        how_to_access: "Call to apply",
        website: "https://(No direct link, call Southwest Airlines)",
        audience: "senior",
      },
      {
        name: "British Airways AARP Discount",
        type: "Discount",
        discount: "Up to $200 off flights",
        eligibility: "AARP members",
        how_to_access: "Book travel via AARP link",
        website: "https://(Link provided in article, but not direct BA link)",
        audience: "senior",
      },
      {
        name: "United Airlines Senior Discount",
        type: "Discount",
        discount: "Various discounts (call to apply)",
        eligibility: "65 and up",
        how_to_access: "Call to apply",
        website: "https://(No direct link, call United Airlines)",
        audience: "senior",
      },
      {
        name: "Alamo Car Rental AARP Discount",
        type: "Discount",
        discount: "Up to 25% off",
        eligibility: "AARP members",
        how_to_access: "Use AARP membership",
        website: "https://(No direct link, use Alamo website with AARP)",
        audience: "senior",
      },
      {
        name: "Avis Senior Discounts (AARP)",
        type: "Discount",
        discount: "$10-$25 off",
        eligibility: "AARP members",
        how_to_access: "Use AARP membership",
        website: "https://(No direct link, use Avis website with AARP)",
        audience: "senior",
      },
      {
        name: "Budget Rent-A-Car Senior Discount (AARP)",
        type: "Discount",
        discount: "10-25% off",
        eligibility: "AARP members (50+)",
        how_to_access: "Use Budget Customer Discount (BCD) # Y508537",
        website: "https://(No direct link, use Budget website with BCD)",
        audience: "senior",
      },
      {
        name: "Dollar Rent-A-Car Senior Discount",
        type: "Discount",
        discount: "10% off",
        eligibility: "50+",
        how_to_access: "In-person or online",
        website: "https://(No direct link, use Dollar website)",
        audience: "senior",
      },
      {
        name: "Hertz Senior Discount",
        type: "Discount",
        discount: "Exclusive rental car deals",
        eligibility: "Renters 50+",
        how_to_access: "Use discount code CDP# 2007815",
        website: "https://(No direct link, use Hertz website with CDP)",
        audience: "senior",
      },
      {
        name: "Payless Senior Discount (AARP)",
        type: "Discount",
        discount: "5% off",
        eligibility: "AARP members",
        how_to_access: "Use Payless Promo Code KW47RY",
        website: "https://(No direct link, use Payless website with promo code)",
        audience: "senior",
      },
      {
        name: "Best Western Senior Discount",
        type: "Discount",
        discount: "10% or more",
        eligibility: "AARP or senior guests (55+)",
        how_to_access: "In-person or online",
        website: "https://(No direct link, use Best Western website)",
        audience: "senior",
      },
      {
        name: "Cambria Suites Senior Discount (Choice Hotels)",
        type: "Discount",
        discount: "Up to 10% off",
        eligibility: "60+ or AARP member",
        how_to_access: "Select \u201cSenior/AARP\u201d from special rate dropdown or call 800-4CHOICE",
        website: "https://(No direct link, use Choice Hotels website)",
        audience: "senior",
      },
      {
        name: "Candlewood Suites Senior Discount",
        type: "Discount",
        discount: "Varies",
        eligibility: "62+",
        how_to_access: "In-person or online",
        website: "https://(No direct link, use Candlewood Suites website)",
        audience: "senior",
      },
      {
        name: "Clarion Hotels Senior Discount (Choice Hotels)",
        type: "Discount",
        discount: "Up to 10% off",
        eligibility: "60+ or AARP member",
        how_to_access: "Select \u201cSenior/AARP\u201d from special rate dropdown or call 800-4CHOICE",
        website: "https://(No direct link, use Choice Hotels website)",
        audience: "senior",
      },
      {
        name: "Comfort Inn Senior Discount (Choice Hotels)",
        type: "Discount",
        discount: "Up to 10% off",
        eligibility: "60+ or AARP member",
        how_to_access: "Select \u201cSenior/AARP\u201d from special rate dropdown or call 800-4CHOICE",
        website: "https://(No direct link, use Choice Hotels website)",
        audience: "senior",
      },
      {
        name: "Comfort Suites Senior Discount (Choice Hotels)",
        type: "Discount",
        discount: "Up to 10% off",
        eligibility: "60+ or AARP member",
        how_to_access: "Select \u201cSenior/AARP\u201d from special rate dropdown or call 800-4CHOICE",
        website: "https://(No direct link, use Choice Hotels website)",
        audience: "senior",
      },
      {
        name: "Crown Plaza Senior Discount",
        type: "Discount",
        discount: "Varies",
        eligibility: "62+",
        how_to_access: "In-person or online",
        website: "https://(No direct link, use Crown Plaza website)",
        audience: "senior",
      },
      {
        name: "Days Inn Senior Discount",
        type: "Discount",
        discount: "Varies",
        eligibility: "60+",
        how_to_access: "In-person or call 1-800-225-3297 and request \u201csenior rate\u201d",
        website: "https://(No direct link, use Days Inn website)",
        audience: "senior",
      },
      {
        name: "Hampton Inn & Suites AARP Discount",
        type: "Discount",
        discount: "10% off",
        eligibility: "AARP members",
        how_to_access: "Use AARP membership",
        website: "https://(No direct link, use Hampton Inn & Suites website)",
        audience: "senior",
      },
      {
        name: "Holiday Inn Senior Discounts",
        type: "Discount",
        discount: "Varies",
        eligibility: "62+ or valid membership ID of a retired persons organization",
        how_to_access: "In-person or online",
        website: "https://(No direct link, use Holiday Inn website)",
        audience: "senior",
      },
      {
        name: "Howard Johnson Hotel Discounts",
        type: "Discount",
        discount: "Off best available rate",
        eligibility: "60+",
        how_to_access: "In-person or call 1-800-225-3297 and request \u201csenior rate\u201d",
        website: "https://(No direct link, use Howard Johnson website)",
        audience: "senior",
      },
      {
        name: "Hyatt Senior Discounts",
        type: "Discount",
        discount: "Up to 50% off",
        eligibility: "62+",
        how_to_access: "In-person or online",
        website: "https://(No direct link, use Hyatt website)",
        audience: "senior",
      },
      {
        name: "Knights Inn Senior Discount",
        type: "Discount",
        discount: "Up to 10% off",
        eligibility: "60+",
        how_to_access: "In-person or online",
        website: "https://(No direct link, use Knights Inn website)",
        audience: "senior",
      },
      {
        name: "La Quinta Inn Senior Discount",
        type: "Discount",
        discount: "Varies",
        eligibility: "65+",
        how_to_access: "In-person or online",
        website: "https://(No direct link, use La Quinta Inn website)",
        audience: "senior",
      },
      {
        name: "Marriott Senior Discount",
        type: "Discount",
        discount: "15% off",
        eligibility: "62+",
        how_to_access: "In-person or online",
        website: "https://(No direct link, use Marriott website)",
        audience: "senior",
      },
      {
        name: "Motel 6 Senior Discount",
        type: "Discount",
        discount: "10% off",
        eligibility: "60+",
        how_to_access: "In-person or online",
        website: "https://(No direct link, use Motel 6 website)",
        audience: "senior",
      },
      {
        name: "Sleep Inn Senior Discount (Choice Hotels)",
        type: "Discount",
        discount: "Up to 10% off",
        eligibility: "60+ or AARP member",
        how_to_access: "Select \u201cSenior/AARP\u201d from special rate dropdown or call 800-4CHOICE",
        website: "https://(No direct link, use Choice Hotels website)",
        audience: "senior",
      },
      {
        name: "Super 8 Senior Discount",
        type: "Discount",
        discount: "10% off (up to 20% with AARP card)",
        eligibility: "Seniors (AARP members for 20%)",
        how_to_access: "In-person or online",
        website: "https://(No direct link, use Super 8 website)",
        audience: "senior",
      },
      {
        name: "Travelodge Senior Discount",
        type: "Discount",
        discount: "Varies",
        eligibility: "60+",
        how_to_access: "In-person or online",
        website: "https://(No direct link, use Travelodge website)",
        audience: "senior",
      },
      {
        name: "Wyndham Hotels AARP Discount",
        type: "Discount",
        discount: "Up to 20% off",
        eligibility: "AARP members",
        how_to_access: "Use AARP card",
        website: "https://(No direct link, use Wyndham Hotels website)",
        audience: "senior",
      },
      {
        name: "Cruise Line Senior Discounts (Carnival, Norwegian, Celebrity, Royal Caribbean)",
        type: "Discount",
        discount: "Varies (call to inquire)",
        eligibility: "55+ (AARP membership often helps)",
        how_to_access: "Call preferred cruise line",
        website: "https://(No direct link, contact cruise lines directly)",
        audience: "senior",
      },
      {
        name: "Greyhound Senior Discount",
        type: "Discount",
        discount: "5% off",
        eligibility: "62+",
        how_to_access: "In-person or online",
        website: "https://(No direct link, use Greyhound website)",
        audience: "senior",
      },
      {
        name: "Amtrak Senior Discounts",
        type: "Discount",
        discount: "15% off lowest available rail fare (most Amtrak trains), 10% off cross-border services (Amtrak and V",
        eligibility: "62+ (15% discount), 60+ (10% discount on cross-border)",
        how_to_access: "In-person or online",
        website: "https://(No direct link, use Amtrak website)",
        audience: "senior",
      },
    ],
  },
  {
    id: "entertainment-leisure",
    category: "Entertainment & Leisure",
    icon: "Ticket",
    coupons: [
      {
        name: "Disabled-World",
        type: "List of discounted and free access passes",
        discount: "Varies (e.g., free access, percentage off)",
        eligibility: "Individuals with disabilities",
        how_to_access: "Visit website, browse listings for specific venues (nature parks, museums, cinemas, etc.).",
        website: "https://www.disabled-world.com/entertainment/discounts/",
        audience: "disability",
        notes: "Focuses on access passes and discounts for various activities and services.",
      },
      {
        name: "Disneyland for Guests with Disabilities",
        type: "Accommodations, guides, potentially reduced admission (needs",
        discount: "Assistive Listening systems, Sign Language interpretation, Video Captioning, guides",
        eligibility: "Guests with disabilities",
        how_to_access: "Download guides, find copies at Disneyland Guest Services locations",
        website: "https://disneyland.disney.go.com/guest-services/guests-with-disabilities/",
        audience: "disability",
        notes: "Offers several guides to help make visits easier and more enjoyable.",
      },
      {
        name: "U.S. Library of Congress \"Talking Books\" Program & National Federation of the Bl",
        type: "Free services/materials",
        discount: "Free braille books, audiobooks, magazines, audio equipment, free newspaper/magazine reading service",
        eligibility: "Those with vision or physical impairments",
        how_to_access: "Through local braille and talking book library (BARD), nfbnewslineonline.org",
        website: "https://www.loc.gov/nls/ and https://nfbnewslineonline.org/",
        audience: "disability",
        notes: "BARD is a web-based service for registered users.",
      },
      {
        name: "Various Movie Theaters, Museums, Zoos, Theme Parks, Aquariums",
        type: "Reduced admission",
        discount: "Reduced admission",
        eligibility: "People with disabilities or their carers",
        how_to_access: "In-person, inquire at venue",
        website: "https://Varies by venue",
        audience: "disability",
        notes: "Most provide reduced admission.",
      },
      {
        name: "AMC Theatres",
        type: "Senior Discount",
        discount: "Discounted movie tickets at select locations",
        eligibility: "60+ years",
        how_to_access: "In-store",
        website: "https://www.amctheatres.com/",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
      {
        name: "Ancestry",
        type: "AARP Discount",
        discount: "Save 30% on a World Explorer or All Access membership for the first year",
        eligibility: "AARP member",
        how_to_access: "Online",
        website: "https://www.ancestry.com/",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
      {
        name: "Cinemark Theatres",
        type: "Senior Discount",
        discount: "Discounted movie ticket for Senior's Day and the Early Bird special",
        eligibility: "62+ years for Senior's Day",
        how_to_access: "In-store",
        website: "https://www.cinemark.com/",
        audience: "senior",
        notes: "Discount availability: Contact local theater for schedule",
      },
      {
        name: "Marcus Theatres and Movie Tavern",
        type: "Senior Special",
        discount: "Young at Heart special: $6.00 for any show that starts before 5:30 p.m.",
        eligibility: "60+ years",
        how_to_access: "In-store",
        website: "https://www.marcustheatres.com/",
        audience: "senior",
        notes: "Discount availability: Every Friday",
      },
      {
        name: "National Parks America the Beautiful Senior Pass",
        type: "Park Pass",
        discount: "$80 lifetime park pass provides admittance to more than 2,000 recreation sites",
        eligibility: "62+ years; must provide proof of age and residency or citizenship. A $10 fee applies to passes bought online or by mail",
        how_to_access: "Online, in-person, or by mail",
        website: "https://www.nps.gov/planyourvisit/passes.htm",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
      {
        name: "Regal Cinemas AARP Movie Tickets",
        type: "AARP Discount",
        discount: "Save up to 20% on Regal ePremiere tickets purchased online",
        eligibility: "AARP member",
        how_to_access: "Online",
        website: "https://www.regmovies.com/",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
      {
        name: "Regal Cinemas Senior Citizen Movie Tickets",
        type: "Senior Discount",
        discount: "Discounted movie tickets at select locations",
        eligibility: "60+ years",
        how_to_access: "In-store",
        website: "https://www.regmovies.com/",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
      {
        name: "Regal Cinemas Concession",
        type: "AARP Discount",
        discount: "$3 off popcorn and soda combo",
        eligibility: "AARP members and Regal Crown Club members",
        how_to_access: "In-store",
        website: "https://www.regmovies.com/",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
      {
        name: "Showcase Cinemas",
        type: "Senior Discount",
        discount: "Discount admission at select theaters; popcorn and soda for $4.50",
        eligibility: "60+ years",
        how_to_access: "In-store",
        website: "https://www.showcasecinemas.com/",
        audience: "senior",
        notes: "Discount availability: Every day",
      },
      {
        name: "America the Beautiful Access Pass",
        type: "Park Pass",
        discount: "Free lifetime pass provides admittance to over 2,000 recreation sites",
        eligibility: "U.S. citizens or permanent residents with a diagnosed permanent disability",
        how_to_access: "Online, in-person, or by mail; requires documentation of permanent disability",
        website: "https://www.nps.gov/planyourvisit/passes.htm",
        audience: "disability",
        notes: "N/A",
      },
      {
        name: "Museum of Contemporary Art San Diego (MCASD) Disability Discount",
        type: "Free Admission",
        discount: "Free admission",
        eligibility: "Visitors with disabilities",
        how_to_access: "In-person",
        website: "https://mcasd.org/",
        audience: "disability",
      },
      {
        name: "The Guggenheim Disability Discount",
        type: "Discounted Admission",
        discount: "Discounted admission for disabled person, free access for care partner",
        eligibility: "Someone with a disability",
        how_to_access: "In-person",
        website: "https://secure.guggenheim.org/events/eebc4350-d2be-3a38-53e0-1da118a7fe49",
        audience: "disability",
      },
      {
        name: "The Museum of Contemporary Art (Chicago) Disability Discount",
        type: "Free Admission",
        discount: "Free admission",
        eligibility: "Visitors with disabilities and their caregivers",
        how_to_access: "In-person",
        website: "https://visit.mcachicago.org/visit/accessibility/",
        audience: "disability",
      },
      {
        name: "Portland Art Museum Disability Discount",
        type: "Free Admission",
        discount: "Free admission for companions and care providers",
        eligibility: "Companions and care providers of disabled visitors",
        how_to_access: "In-person",
        website: "https://portlandartmuseum.org/accessibility/",
        audience: "disability",
      },
      {
        name: "Disneyland Paris Disability Discount",
        type: "Discount",
        discount: "25% discount, priority access to rides, attractions, and food lines",
        eligibility: "Visitors with disabilities (application and verification required)",
        how_to_access: "Apply ahead of time",
        website: "https://tickets.disneylandparis.com/en-usd/tickets-guests-with-disabilities",
        audience: "disability",
      },
      {
        name: "Arc de Triomphe Disability Discount (France)",
        type: "Free Admission",
        discount: "Free admission for disabled person and one companion",
        eligibility: "Disabled person and one companion",
        how_to_access: "In-person",
        website: "https://www.paris-arc-de-triomphe.fr/en/visit/visitors-with-disabilities",
        audience: "disability",
      },
      {
        name: "Brooklyn Botanic Garden Disability Discount",
        type: "Free Admission",
        discount: "Free admission for a personal care assistant",
        eligibility: "Personal care assistant accompanying a disabled visitor",
        how_to_access: "In-person",
        website: "https://www.showclix.com/event/brooklyn-botanic-garden-admission-2025gxwpp0y",
        audience: "disability",
      },
      {
        name: "Coastal Maine Botanical Gardens Disability Discount",
        type: "Free Admission",
        discount: "Free admission for a personal care assistant",
        eligibility: "Personal care assistant accompanying a disabled visitor",
        how_to_access: "In-person",
        website: "https://www.mainegardens.org/visit/inclusion-and-accessibility/",
        audience: "disability",
      },
    ],
  },
  {
    id: "utilities-home",
    category: "Utilities & Home",
    icon: "Home",
    coupons: [
      {
        name: "California Alternate Rates for Energy (CARE) Program / Family Electric Rate Assi",
        type: "Utility Bill Discount",
        discount: "30-35% discount on electric bill, 20% discount on natural gas bill",
        eligibility: "Income-qualified households, including those with elderly or disabled members. Eligibility requirements vary by utility ",
        how_to_access: "Apply through your utility provider (e.g., PG&E, SCE) or contact the California Public Utilities Commission.",
        website: "https://www.cpuc.ca.gov/industries-and-topics/electrical-energy/electric-costs/care-fera-program",
        audience: "both",
        notes: "These are state-specific programs in California. Similar programs may exist in other states; customers should check with their local utility providers.",
      },
      {
        name: "Low-Income Home Energy Assistance Program (LIHEAP)",
        type: "Financial assistance (grants/bill credits)",
        discount: "Varies based on income, household size, and energy costs",
        eligibility: "Low-income households, with priority often given to households with elderly, disabled, or young children",
        how_to_access: "Apply through local or state LIHEAP agencies",
        website: "https://liheapch.acf.hhs.gov/ (LIHEAP Clearinghouse)",
        audience: "both",
        notes: "Federally funded program to help eligible households with heating and cooling costs.",
      },
      {
        name: "Low Income Home Energy Assistance Program (LIHEAP)",
        type: "Utility bill assistance",
        discount: "Varies based on income and household size",
        eligibility: "Low-income households, often includes seniors and disabled individuals",
        how_to_access: "Apply through state or local energy assistance offices",
        website: "https://liheapch.acf.hhs.gov/",
        audience: "both",
        notes: "Helps with heating and cooling costs.",
      },
      {
        name: "Various U.S. Utility Company Discounts",
        type: "Discount/Rebate",
        discount: "Discounts on electric, gas, phone, water, and trash services",
        eligibility: "Customers with disabilities, seniors, the elderly, or low-income singles and families",
        how_to_access: "Contact individual utility companies",
        website: "https://Varies by company",
        audience: "both",
        notes: "Many U.S. utility companies offer discounts.",
      },
      {
        name: "AT&T 55+ Plan",
        type: "Senior Plan",
        discount: "Plans start at $60 per month (single line only) or $80 per month for two lines ($40 per line)",
        eligibility: "55+ years, Florida residents only",
        how_to_access: "Online, In-store",
        website: "https://www.att.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Consumer Cellular",
        type: "Senior Plan / AARP Discount",
        discount: "Unlimited Talk with Text and Data plan starts at $20 monthly for 1 GB of data. AARP members get a fi",
        eligibility: "AARP member for additional discounts",
        how_to_access: "Online",
        website: "https://www.consumercellular.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Lively",
        type: "Senior Plan / AARP Discount",
        discount: "AARP members can now save $60 per year on select plans.",
        eligibility: "AARP member for additional discounts",
        how_to_access: "Online",
        website: "https://www.lively.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "Verizon 55+ Unlimited Plan",
        type: "Senior Plan",
        discount: "Unlimited calls, texts, and data for $60 a month (single line only) or $80 per month for two lines (",
        eligibility: "55+ years, Florida residents only",
        how_to_access: "Online, In-store",
        website: "https://www.verizon.com/",
        audience: "senior",
        notes: "N/A",
      },
      {
        name: "T-Mobile Unlimited 55+ Plans",
        type: "Senior Plan",
        discount: "Three Unlimited 55+ plans to choose from with unlimited talk, text, and smartphone data: the Essenti",
        eligibility: "55+ years",
        how_to_access: "Online, In-store",
        website: "https://www.t-mobile.com/",
        audience: "senior",
        notes: "Available in all 50 states, Washington, D.C., and Puerto Rico.",
      },
      {
        name: "AARP Vehicle and Property Insurance Discounts",
        type: "AARP Membership Benefits",
        discount: "Discounts on auto and homeowners insurance",
        eligibility: "AARP member",
        how_to_access: "Online",
        website: "https://www.aarp.org/",
        audience: "senior",
        notes: "Provided through The Hartford",
      },
      {
        name: "Lifeline Program",
        type: "Government Assistance",
        discount: "Makes communication services more affordable for low-income consumers",
        eligibility: "Low-income consumers, including many seniors and disabled individuals",
        how_to_access: "Apply through participating phone carriers; check eligibility by city/state or ZIP code",
        website: "https://www.lifeline.gov/",
        audience: "both",
        notes: "Federal Communications Commission (FCC) program",
      },
    ],
  },
  {
    id: "coupon-aggregators",
    category: "Coupon Aggregators",
    icon: "Globe",
    coupons: [
      {
        name: "DisabledDeals.com",
        type: "Coupon Aggregator",
        discount: "Various discounts and deals",
        eligibility: "People with disabilities",
        how_to_access: "Online platform",
        website: "https://disableddeals.com/",
        audience: "disability",
        notes: "N/A",
      },
      {
        name: "BenefitsCheckup.org",
        type: "Information Resource",
        discount: "Helps find various benefits and savings programs",
        eligibility: "Seniors and people with disabilities",
        how_to_access: "Online platform",
        website: "https://www.benefitscheckup.org/",
        audience: "both",
        notes: "N/A",
      },
    ],
  },
];

export const TOTAL_COUPONS = 212;
